### ISSUE TITLE
The UCB algorithm is a little different from the paper

### ISSUE THREAD

**Issue by tobegit3hub** [haroldsultan/MCTS#2]
According to the paper [A Survey of Monte Carlo Tree Search Methods](http://pubs.doc.ic.ac.uk/survey-mcts-methods/survey-mcts-methods.pdf), the UCB function should look like this.

And here is the pseudo-code about the implementation.

![Uploading Screen Shot 2017-10-25 at 4.58.17 PM.png…]()

The coefficient `2` should be outsize of the `log`. And this line of code is a little different from the paper https://github.com/haroldsultan/MCTS/blob/master/mcts.py#L115 .

**Comment by haroldsultan** [comment]
thanks.  i corrected the code

**Comment by tobegit3hub** [comment]
Great and thanks for your sharing 🎉
